<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('roles', function (Blueprint $table) {
            $table->id();
            $table->string('name')->nullable();
            $table->text('description')->nullable();
            $table->text('product_view')->nullable();
            $table->text('product_add')->nullable();
            $table->text('product_edit')->nullable();
            $table->text('product_delete')->nullable();
            $table->text('purchase_view')->nullable();
            $table->text('purchase_add')->nullable();
            $table->text('purchase_edit')->nullable();
            $table->text('purchase_delete')->nullable();
            $table->text('purchase_pymt_view')->nullable();
            $table->text('purchase_pymt_add')->nullable();
            $table->text('purchase_pymt_edit')->nullable();
            $table->text('purchase_pymt_delete')->nullable();
            $table->text('sale_view')->nullable();
            $table->text('sale_add')->nullable();
            $table->text('sale_edit')->nullable();
            $table->text('sale_delete')->nullable();
            $table->text('sale_pymt_view')->nullable();
            $table->text('sale_pymt_add')->nullable();
            $table->text('sale_pymt_edit')->nullable();
            $table->text('sale_pymt_delete')->nullable();
            $table->text('expense_view')->nullable();
            $table->text('expense_add')->nullable();
            $table->text('expense_edit')->nullable();
            $table->text('expense_delete')->nullable();
            $table->text('quotation_view')->nullable();
            $table->text('quotation_add')->nullable();
            $table->text('quotation_edit')->nullable();
            $table->text('quotation_delete')->nullable();
            $table->text('transfer_view')->nullable();
            $table->text('transfer_add')->nullable();
            $table->text('transfer_edit')->nullable();
            $table->text('transfer_delete')->nullable();
            $table->text('sale_return_view')->nullable();
            $table->text('sale_return_add')->nullable();
            $table->text('sale_return_edit')->nullable();
            $table->text('sale_return_delete')->nullable();
            $table->text('purchase_return_view')->nullable();
            $table->text('purchase_return_add')->nullable();
            $table->text('purchase_return_edit')->nullable();
            $table->text('purchase_return_delete')->nullable();
            $table->text('employee_view')->nullable();
            $table->text('employee_add')->nullable();
            $table->text('employee_edit')->nullable();
            $table->text('employee_delete')->nullable();
            $table->text('user_view')->nullable();
            $table->text('user_add')->nullable();
            $table->text('user_edit')->nullable();
            $table->text('user_delete')->nullable();
            $table->text('customer_view')->nullable();
            $table->text('customer_add')->nullable();
            $table->text('customer_edit')->nullable();
            $table->text('customer_delete')->nullable();
            $table->text('biller_add')->nullable();
            $table->text('biller_view')->nullable();
            $table->text('biller_edit')->nullable();
            $table->text('biller_delete')->nullable();
            $table->text('supplier_add')->nullable();
            $table->text('supplier_view')->nullable();
            $table->text('supplier_edit')->nullable();
            $table->text('supplier_delete')->nullable();
            $table->text('dshbrd_proft_smry')->nullable();
            $table->text('dshbrd_cash_flow')->nullable();
            $table->text('dshbrd_mnth_smry')->nullable();
            $table->text('dshbrd_yr_rprt')->nullable();
            $table->text('acc_account')->nullable();
            $table->text('acc_mny_tnsfr')->nullable();
            $table->text('acc_blnce_sheet')->nullable();
            $table->text('acc_account_stmt')->nullable();
            $table->text('hrm_dept')->nullable();
            $table->text('hrm_atndce')->nullable();
            $table->text('hrm_payroll')->nullable();
            $table->text('hrm_holiday')->nullable();
            $table->text('rpt_smry')->nullable();
            $table->text('rpt_best_seller')->nullable();
            $table->text('rpt_daily_sale')->nullable();
            $table->text('rpt_mnth_sale')->nullable();
            $table->text('rpt_daily_purchse')->nullable();
            $table->text('rpt_mnth_purchse')->nullable();
            $table->text('rpt_product')->nullable();
            $table->text('rpt_payment')->nullable();
            $table->text('rpt_purchse')->nullable();
            $table->text('rpt_sale')->nullable();
            $table->text('rpt_sale_chrt')->nullable();
            $table->text('rpt_warehouse')->nullable();
            $table->text('rpt_warehouse_chrt')->nullable();
            $table->text('rpt_product_expry')->nullable();
            $table->text('rpt_dailysale_obj')->nullable();
            $table->text('rpt_product_qty')->nullable();
            $table->text('rpt_user')->nullable();
            $table->text('rpt_customer')->nullable();
            $table->text('rpt_customer_due')->nullable();
            $table->text('rpt_supplier')->nullable();
            $table->text('rpt_supplier_due')->nullable();
            $table->text('Seting_cstm_feld')->nullable();
            $table->text('Seting_all_notifctn')->nullable();
            $table->text('Seting_send_notifctn')->nullable();
            $table->text('Seting_dscnt')->nullable();
            $table->text('Seting_warehouse')->nullable();
            $table->text('Seting_custmr_grp')->nullable();
            $table->text('Seting_brand')->nullable();
            $table->text('Seting_unit')->nullable();
            $table->text('Seting_currency')->nullable();
            $table->text('Seting_tax')->nullable();
            $table->text('Seting_generl')->nullable();
            $table->text('Seting_mail')->nullable();
            $table->text('Seting_sms')->nullable();
            $table->text('Seting_create_sms')->nullable();
            $table->text('Seting_pos')->nullable();
            $table->text('Seting_hrm')->nullable();
            $table->text('Seting_reward_point')->nullable();
            $table->text('misc_category')->nullable();
            $table->text('misc_delivery')->nullable();
            $table->text('misc_stockcnt')->nullable();
            $table->text('misc_adjust')->nullable();
            $table->text('misc_giftcard')->nullable();
            $table->text('misc_coupon')->nullable();
            $table->text('misc_prodct_histry')->nullable();
            $table->text('misc_pbarcode')->nullable();
            $table->text('misc_emp_db')->nullable();
            $table->text('misc_today_sale')->nullable();
            $table->text('misc_today_profit')->nullable();
            $table->string('company_id')->nullable();
            $table->string('created_by')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('roles');
    }
};
